name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Send Test Metric to OpenTelemetry
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://YOUR_EC2_IP:4318/v1/metrics"
        run: |
          curl -X POST $OTEL_EXPORTER_OTLP_ENDPOINT -H "Content-Type: application/json" -d '{
            "resourceMetrics": [
              {
                "resource": {
                  "attributes": [
                    {"key": "service.name", "value": {"stringValue": "github-actions-test"}}
                  ]
                },
                "scopeMetrics": [
                  {
                    "metrics": [
                      {
                        "name": "github_action_execution",
                        "unit": "count",
                        "sum": {"dataPoints": [{"asInt": 1}]}
                      }
                    ]
                  }
                ]
              }
            ]
          }'

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r * $USER@$HOST:~/app/
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            command -v node >/dev/null 2>&1 || curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo bash - && sudo apt install -y nodejs
            command -v pm2 >/dev/null 2>&1 || npm install -g pm2
            cd ~/app
            npm install
            pm2 restart all || pm2 start index.js
          EOF

